# coding: utf-8
import pathlib,json,base64,hashlib
root=pathlib.Path('.');assets=root/'prototype/fx-lab-assets'
choices=[('balloon','气球 · Lukeo135',assets/'balloon.mp3','https://freesound.org/people/Lukeo135/sounds/563197/','公开 HQ MP3 预览，非原 WAV'),('balloon2','气球 · Breviceps',assets/'balloon2.mp3','https://freesound.org/people/Breviceps/sounds/458398/','公开 HQ MP3 预览，非原 WAV'),('impact','Kenney · Generic light',assets/'impactGeneric_light_000.ogg','https://kenney.nl/assets/impact-sounds','impactGeneric_light_000.ogg'),('pluck','Kenney · Pluck',assets/'pluck_001.ogg','https://kenney.nl/assets/interface-sounds','pluck_001.ogg')]
data=[]
for id,label,p,url,note in choices:
 raw=p.read_bytes();data.append(dict(id=id,label=label,source=url,note=note,license='CC0 1.0',sha256=hashlib.sha256(raw).hexdigest(),base64=base64.b64encode(raw).decode()))
levels=json.loads((root/'prototype/chain-shot-v0.3-levels.json').read_text(encoding='utf8'))
html='''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Chain Shot · FX Lab</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#eeece5;color:#243a32;font:15px system-ui,sans-serif}main{max-width:760px;margin:auto;padding:24px 18px}h1{font-size:25px;margin:0 0 6px}p{color:#65736b;line-height:1.6}section{background:#faf8f1;border:1px solid #d8ddd3;border-radius:18px;padding:16px;margin:16px 0}label{display:block;margin:10px 0}select,button{font:inherit;border:1px solid #becbbe;background:#f4f2e9;color:#243a32;border-radius:10px;padding:11px;min-height:44px;max-width:100%}select{width:100%}button{cursor:pointer}button:disabled{opacity:.5}.row{display:flex;flex-wrap:wrap;gap:8px}.row label{margin:4px 0}canvas{display:block;width:100%;height:430px;background:#faf8f1;border-radius:12px}#status{min-height:25px;font-size:13px}a{color:#387658}small{color:#65736b}details{font-size:13px;line-height:1.6}input{accent-color:#408667}button.active{background:#d5e9da;border-color:#408667}@media(max-width:400px){main{padding:16px 10px}canvas{height:390px}section{padding:12px}}
</style><main><h1>CHAIN SHOT · FX LAB</h1><p>同一命中时间线，比较 Pop 的质感与破裂瞬间。独立实验，不修改主游戏。</p>
<section><label>候选素材<select id="sample"></select></label><small id="source"></small><div class="row"><label><input id="body" type="checkbox"> 轻低频层</label><label><input id="synth" type="checkbox"> 叠加 V0.3 合成 Hit</label><label><input id="mute" type="checkbox"> 静音看动画</label></div><div class="row"><button id="single">单次命中</button><button id="twelve">连续 12 次 · 120ms 间隔</button><button id="baseline">只听 V0.3 Hit</button></div></section>
<section><div class="row"><button id="classic" class="active">Classic+Pop</button><button id="blast">Balloon Blast</button><button id="stop">停止 / 重置</button></div><canvas id="stage" aria-label="命中动画实验"></canvas><div id="status" role="status">选择素材，点击试听。首次点击解锁声音。</div><div class="row"><button id="medium">原第 6 关 · 同 Seed</button><button id="dense">原第 10 关 · 同 Seed</button></div></section>
<details><summary>来源、固定参数与试听边界</summary><div id="credits"></div><p>所有候选按峰值归一至0.7，自动去掉前导静音，取最多140ms，尾端8ms淡出；主增益0.55，压缩器限制密集混音。不是响度LUFS匹配。无随机升调；每次重播使用相同素材与时间线。Pop先安排，合成层独立限额，不抢Pop声部。同刻多个节点合并为一个Pop重音，保留每个节点的视觉命中。音画共用AudioContext输出时钟，视觉误差受显示刷新率与设备延迟影响。</p><p>气球原始WAV需登录，此处使用已下载CC0录音的公开HQ预览。素材已成功解码与测试；耳机/手机扬声器主观听感尚需你确认。原始录音和授权记录在fx-lab-assets。</p></details></main>
<script>
'use strict';
const ASSETS=__ASSETS__,BOARDS=__BOARDS__,D={U:[0,-1],D:[0,1],L:[-1,0],R:[1,0],UL:[-1,-1],UR:[1,-1],DL:[-1,1],DR:[1,1]};
const $=id=>document.getElementById(id),canvas=$('stage'),ctx=canvas.getContext('2d');let ac,master,limiter,buffers={},mode='classic',events=[],nodes=[],epoch=0,end=0,sources=[],readyPromise,lastPreset='single',stats={};
for(const a of ASSETS){const o=document.createElement('option');o.value=a.id;o.textContent=a.label;$('sample').append(o);const p=document.createElement('p'),link=document.createElement('a');link.href=a.source;link.target='_blank';link.rel='noopener';link.textContent=a.label+' · CC0';p.append(link,document.createTextNode(' — '+a.note));$('credits').append(p)}
function sourceLabel(){const a=ASSETS.find(a=>a.id===$('sample').value);$('source').textContent=a.note+' · CC0 1.0'}sourceLabel();$('sample').onchange=sourceLabel;
async function unlock(){if(!ac){ac=new (window.AudioContext||window.webkitAudioContext)();master=ac.createGain();master.gain.value=.55;limiter=ac.createDynamicsCompressor();limiter.threshold.value=-12;limiter.knee.value=3;limiter.ratio.value=12;limiter.attack.value=.002;limiter.release.value=.08;master.connect(limiter);limiter.connect(ac.destination)}await ac.resume();if(!readyPromise)readyPromise=Promise.all(ASSETS.map(async a=>{const raw=Uint8Array.from(atob(a.base64),c=>c.charCodeAt(0));const b=await ac.decodeAudioData(raw.buffer);buffers[a.id]=prepare(b)}));await readyPromise}
function prepare(b){let peak=0;for(let c=0;c<b.numberOfChannels;c++)for(const v of b.getChannelData(c))peak=Math.max(peak,Math.abs(v));let onset=0;for(let i=0;i<b.length;i++){let v=0;for(let c=0;c<b.numberOfChannels;c++)v=Math.max(v,Math.abs(b.getChannelData(c)[i]));if(v>peak*.12){onset=Math.max(0,i-Math.round(b.sampleRate*.001));break}}const length=Math.min(b.length-onset,Math.round(b.sampleRate*.14)),out=ac.createBuffer(b.numberOfChannels,length,b.sampleRate);for(let c=0;c<b.numberOfChannels;c++){const x=b.getChannelData(c),y=out.getChannelData(c);for(let i=0;i<length;i++)y[i]=x[i+onset]*(.7/(peak||1))*Math.min(1,(length-1-i)/(b.sampleRate*.008))}return out}
function stop(){for(const s of sources){try{s.stop()}catch(e){}}sources=[];events=[];nodes=[];epoch=0;end=0;stats={};$('status').textContent='已停止。可直接重播比较。'}
function heardTime(){if(!ac)return 0;const stamp=ac.getOutputTimestamp?ac.getOutputTimestamp():null;if(stamp&&stamp.contextTime>0)return stamp.contextTime+(performance.now()-stamp.performanceTime)/1000;return Math.max(0,ac.currentTime-(ac.baseLatency||0))}
function tone(t,kind,depth){const o=ac.createOscillator(),g=ac.createGain();if(kind==='body'){o.type='triangle';o.frequency.setValueAtTime(100,t);o.frequency.exponentialRampToValueAtTime(45,t+.06)}else{o.type='triangle';o.frequency.setValueAtTime(220*2**([0,2,4,7,9,12,14,16][Math.min(7,depth)]/12),t)}g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(kind==='body'?.045:.032,t+.004);g.gain.exponentialRampToValueAtTime(.0001,t+(kind==='body'?.065:.16));o.connect(g);g.connect(master);o.start(t);o.stop(t+.18);sources.push(o);o.onended=()=>{o.disconnect();g.disconnect()};if(kind==='hit'){const high=ac.createOscillator(),hg=ac.createGain();high.type='sine';high.frequency.setValueAtTime(440*2**([0,2,4,7,9,12,14,16][Math.min(7,depth)]/12),t);hg.gain.setValueAtTime(.0001,t);hg.gain.exponentialRampToValueAtTime(.012,t+.004);hg.gain.exponentialRampToValueAtTime(.0001,t+.05);high.connect(hg);hg.connect(master);high.start(t);high.stop(t+.06);sources.push(high);high.onended=()=>{high.disconnect();hg.disconnect()}}}
function timeline(level){const ns=level.nodes,seen=new Set([level.solution]),ev=[{index:level.solution,time:0,depth:0}],ps=[{...ns[level.solution],source:level.solution,depth:0,waiting:true}];let tick=0,pulses=ps;while(pulses.length&&tick++<200){const moving=pulses;pulses=[];for(const p of moving){if(p.waiting){p.waiting=false;pulses.push(p);continue}const [dx,dy]=D[p.dir];p.x+=dx;p.y+=dy;if(p.x<0||p.x>=7||p.y<0||p.y>=9)continue;ns.forEach((n,i)=>{if(n.x===p.x&&n.y===p.y&&!seen.has(i)){seen.add(i);ev.push({index:i,time:tick*.088,depth:p.depth+1,parent:p.source});pulses.push({...n,source:i,depth:p.depth+1,waiting:true})}});pulses.push(p)}}return {events:ev,duration:tick*.088,nodes:ns}}
let runToken=0;
async function play(preset,onlySynth=false){const token=++runToken;try{await unlock();if(token!==runToken)return;stop();lastPreset=preset;let plan;if(preset==='single')plan={nodes:[{x:3,y:4,dir:'UR'}],events:[{index:0,time:.05,depth:0}],duration:.55};else if(preset==='twelve')plan={nodes:Array.from({length:12},(_,i)=>({x:1+i%4*1.5,y:2+Math.floor(i/4)*2,dir:['UR','D','L','DR'][i%4]})),events:Array.from({length:12},(_,i)=>({index:i,time:.05+i*.12,depth:Math.floor(i/3)})),duration:1.8};else plan=timeline(BOARDS[preset==='medium'?0:1]);nodes=plan.nodes;events=plan.events;epoch=ac.currentTime+.08;end=epoch+plan.duration+.3;stats={hits:events.length,audioGroups:0,events:[],mode,preset,rendered:[]};master.gain.value=$('mute').checked?0:.55;
 const groups=new Map();for(const e of events){const key=e.time.toFixed(5);if(!groups.has(key))groups.set(key,[]);groups.get(key).push(e)}let popEnds=[],layerEnds=[];
 for(const group of groups.values()){const e=group[0],t=epoch+e.time;popEnds=popEnds.filter(x=>x>t);layerEnds=layerEnds.filter(x=>x>t);if(!onlySynth){const b=buffers[$('sample').value],s=ac.createBufferSource(),g=ac.createGain();s.buffer=b;g.gain.value=Math.min(1, .85+group.length*.04);s.connect(g);g.connect(master);s.start(t);sources.push(s);s.onended=()=>{s.disconnect();g.disconnect()};popEnds.push(t+b.duration);stats.audioGroups++;stats.maxPop=Math.max(stats.maxPop||0,popEnds.length)}
 if((onlySynth||$('synth').checked)&&layerEnds.length<=1){tone(t,'hit',e.depth);layerEnds.push(t+.18,t+.06)}if($('body').checked&&layerEnds.length<3){tone(t,'body',e.depth);layerEnds.push(t+.18)}stats.events.push({scheduled:t,count:group.length});stats.maxLayers=Math.max(stats.maxLayers||0,layerEnds.length)}$('status').textContent='播放中 · '+events.length+' 次命中';
 }catch(e){$('status').textContent='音频未能加载：'+e.message;console.error(e)}}
function arrow(x,y,dir,alpha=1){const d=D[dir];ctx.save();ctx.translate(x,y);ctx.rotate(Math.atan2(d[1],d[0]));ctx.globalAlpha=alpha;ctx.strokeStyle='#243a32';ctx.lineWidth=2.7;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();ctx.moveTo(-9,0);ctx.lineTo(9,0);ctx.moveTo(3,-6);ctx.lineTo(9,0);ctx.lineTo(3,6);ctx.stroke();ctx.restore()}
function draw(){const w=canvas.clientWidth,h=canvas.clientHeight,dpr=Math.min(devicePixelRatio||1,2);if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr)}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);const cell=Math.min((w-52)/6,(h-52)/8),x0=(w-cell*6)/2,y0=(h-cell*8)/2,now=heardTime();const ns=nodes.length?nodes:[{x:3,y:4,dir:'UR'}];for(const e of events){if(e.parent===undefined)continue;const origin=events.find(a=>a.index===e.parent),start=origin.time+.088,t=now-epoch;if(t<start||t>e.time+.04)continue;const a=ns[e.parent],b=ns[e.index],q=Math.min(1,(t-start)/(e.time-start)),tail=Math.max(0,q-.16);ctx.strokeStyle='#408667';ctx.lineWidth=3;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(x0+(a.x+(b.x-a.x)*tail)*cell,y0+(a.y+(b.y-a.y)*tail)*cell);ctx.lineTo(x0+(a.x+(b.x-a.x)*q)*cell,y0+(a.y+(b.y-a.y)*q)*cell);ctx.stroke()}for(let i=0;i<ns.length;i++){const n=ns[i],x=x0+n.x*cell,y=y0+n.y*cell,e=events.find(e=>e.index===i),age=e?now-epoch-e.time:-Infinity;if(e&&age>=0&&!e.rendered){e.rendered=true;stats.rendered.push({index:i,delayMs:age*1000})}const ghost=mode==='blast'&&age>=0;let r=18;if(age>=-.045&&age<0)r*=1-.12*(1+age/.045);else if(age>=0&&!ghost)r*=1+.15*Math.exp(-age/ .08)*Math.sin(age*38);ctx.save();ctx.globalAlpha=ghost?.24:1;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fillStyle=ghost?'#faf8f1':age>=0?'#c8e2ce':'#efece3';ctx.fill();ctx.strokeStyle=ghost?'#65736b':'#94b09a';ctx.lineWidth=1.3;ctx.stroke();ctx.restore();arrow(x,y,n.dir,ghost?.32:1);
 if(age>=0&&age<.016){ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(x,y,21,0,Math.PI*2);ctx.fill();arrow(x,y,n.dir,.6)}if(age>=0&&age<.14){const q=age/.14;ctx.save();ctx.globalAlpha=(1-q)*.65;ctx.strokeStyle='#408667';ctx.lineWidth=2*(1-q)+.5;ctx.beginPath();ctx.arc(x,y,19+(1-(1-q)**3)*22,0,Math.PI*2);ctx.stroke();if(mode==='blast')for(let k=0;k<5;k++){const angle=k*2.399+i*.8,dist=12+Math.sqrt(q)*(12+k*2);ctx.save();ctx.translate(x+Math.cos(angle)*dist,y+Math.sin(angle)*dist);ctx.rotate(angle);ctx.fillStyle=k%2?'#96bb9d':'#408667';ctx.beginPath();ctx.moveTo(-3,-2);ctx.lineTo(4,0);ctx.lineTo(0,3);ctx.fill();ctx.restore()}ctx.restore()}}
 if(epoch&&now>end){$('status').textContent='完成 · '+stats.hits+' 次命中 · 可换素材或动画重播'}requestAnimationFrame(draw)}
$('single').onclick=()=>play('single');$('twelve').onclick=()=>play('twelve');$('baseline').onclick=()=>play('twelve',true);$('medium').onclick=()=>play('medium');$('dense').onclick=()=>play('dense');$('stop').onclick=()=>{runToken++;stop()};for(const m of ['classic','blast'])$(m).onclick=()=>{runToken++;stop();mode=m;$('classic').classList.toggle('active',m==='classic');$('blast').classList.toggle('active',m==='blast')};$('mute').onchange=()=>{if(master)master.gain.value=$('mute').checked?0:.55};for(const id of ['sample','body','synth'])$(id).addEventListener('change',()=>{runToken++;stop()});document.addEventListener('visibilitychange',()=>{if(document.hidden){runToken++;stop();if(ac)ac.suspend()}});
if(new URLSearchParams(location.search).has('debug'))window.fxLab={play,stop,timeline,get stats(){return stats},get decoded(){return Object.fromEntries(Object.entries(buffers).map(([k,b])=>[k,{duration:b.duration,length:b.length}]))},get state(){return {mode,clock:ac?.currentTime,heard:heardTime(),epoch,events,nodes,muted:$('mute').checked}}};requestAnimationFrame(draw);
</script></html>'''
html=html.replace('__ASSETS__',json.dumps(data,ensure_ascii=False)).replace('__BOARDS__',json.dumps([levels[5],levels[9]],ensure_ascii=False));(root/'prototype/chain-shot-fx-lab.html').write_text(html,encoding='utf8')
